version: '3.5'

services:
    # VOSK / Kaldi container
    vosk-hsb-wav2vec2:
        image: vosk_server_wav2vec2:latest
        restart: unless-stopped
        environment:
            - ASR_SERVER_INTERFACE
            - ASR_SERVER_PORT
            - ASR_MODEL_NAME
            - ASR_SAMPLE_RATE
            - ASR_VERBOSE_OUTPUT
            - ASR_ONNX
            - ASR_USE_LM
        volumes:
            - ./models:/app/models/
            - ./lm:/app/lm/
            - ./spell:/app/spell/
            
