version: '3.5'

services:
    # VOSK / Kaldi container
    vosk-hsb-wav2vec2:
        image: vosk-hsb-wav2vec2
        restart: unless-stopped
        command: ["python", "-u", "asr_server.py", "--config", "/app/asr_server_config.json"]
        volumes:
            - ./asr_server_config.json:/app/asr_server_config.json:ro
            - ./models/ov_int8:/app/models/ov_int8/
            - ./lm:/app/lm/
            - ./spell:/app/spell/
        ports:
            - "2700:2700"