version: '3.5'

services:
    # VOSK / Kaldi container
    vosk-hsb-recikts:
        image: vosk_server_recikts:latest
        restart: unless-stopped
        environment:
            - VOSK_SAMPLE_RATE
            - VOSK_LOG_AUDIO
            - MODEL_PATH_FULL
            - VOSK_SHOW_WORDS
            - VOSK_SUBWORD_REGEX
        volumes:
            - ./data:/data
            - ./logs:/logs
